### ISSUE TITLE
npms-www: isn't windows-friendly at all

### ISSUE THREAD

**Issue by Den-dp** [nyrosmith/shouldWorkOnWindowsToo#4]
https://github.com/npms-io/npms-www

```
/d/dev/rep/npms-www: npm run build

> npms-www@0.1.0 build D:\dev\rep\npms-www
> ./scripts/build

'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by nyrosmith** [comment]
@Den-dp Can you provide an actual issue on this repo that fullfills the criteria to get listed here?

**Comment by Den-dp** [comment]
@nyrosmith wops, just noticed the second bullet of the "How to add an issue" :open_mouth: 

Some projects are libraries, some are tools. Both requires community to help with project development. For those projects windows-friendly npm scripts is a requirement.

Some projects are services. And almost always they are not meant to work for all because f.e. they are hosted in a cloud with OS that is comfortable for maintainer. In this case there is no requirement to have a windows support for npm scripts…  It's more _nice to have_ than _in priority_.

That's why I'm not sure that this is ok to ask maintainers for such project as npms-www for the windows support (and this is the reason why I haven't created an issue) but nevertheless I can imagine them accepting a PR. And of course I may be wrong with that point of view.

So…what do you think about such a type of projects? Should we ask their maintainers for a windows support?

P.S. Sorry for the long read

**Comment by nyrosmith** [comment]
Good read!
I don't want to add Win support just for the sake of having it. I prefer to solve 'real' issues. If you want to contribute on that repo and it doesnot work on Win you should ask them in the first place.
Just my two cents.

**Comment by Den-dp** [comment]
@nyrosmith thanks for the answer.

I got your point, and totally agree, that "real" issues are more important.

Nevertheless thanks for this project, what you are doing is awesome. Keep it up! :sparkles:

**Comment by nyrosmith** [comment]
Thank you @Den-dp
Please come back if there is something I can do for you.
And as it seems you are using Windows too -> Help is always appreciated!
